### PR TITLE
fix: better link resolution and management

### LINKED ISSUE #73: [feature_request]: Revise link resolution
### What is missing in the theme?

When parsing markdown links, Shadocs will use the `relLangURL` function to resolve URLs. A problem with this is that the function does not handle links relative to the current page. `relref` might be used instead, but it does not correctly handle external links.

It appears that the convention in Hugo is to leave links rendered from markdown as-is, and use the `ref`/`relref` shortcodes when linking to other pages on the website. Shadocs seems to go against this convention by parsing and handling links rendered by markdown, which is admittedly rather convenient. However, because `relLangURL` is used to resolve links, the resulting URL is naively relative to the configured `baseURL`, making it unsuitable for relative paths. The `relref` function is smarter about this, but it doesn't work with external links. Neither function can be used on its own.

To resolve this problem, the link renderer could parse the URL. If it has a scheme, then `relLangURL` is used as before. Otherwise, `relref` is used. To implement this for my website, I made the following change:

https://github.com/Anaminus/shadocs/commit/7982a49fb9a8a588475c2fc9059c63182c4a977f

I'm hesitant to submit this as a Pull Request because links with relative paths are likely to be interpreted differently. Accepting this change would involve users reevaluating all the links on their website, to make sure they are corrected for the new behavior. The effect is wide-reaching enough that it could be considered a breaking change.

### PR DESCRIPTION
**Pull request by jgazeau**
* [x] fix link resolution
* [x] enhance documentation
* [x] add htmltest to test all links of the documentation website

Fixes #73

### CODE REVIEW

**Comment by Anaminus** [comment]
For end-users, it's most important to be able to link to content. That's why I think `relref` should be used. If I were to write `hrefResolver.html`, it might look like this:

```
{{$href := .this.Destination}}
{{if (urls.Parse $href).Scheme | not}}
	{{$href = relref .this.Page $href}}
{{end}}
{{return $href}}
```

The condition is included to fix relref not handling external links properly. If a link has a scheme, then it is passed through directly without any extra processing. This appears to be a good heuristic, but I haven't tested it thoroughly.

Additionally, there appears to be a bug with how relref handles trailing slashes. I'd consider this an upstream issue, but it could potentially be resolved here by just trimming the slash:

```
{{$href := .this.Destination}}
{{if (urls.Parse $href).Scheme | not}}
  {{$href = strings.TrimSuffix "/" $href}}
  {{$href = relref .this.Page $href}}
{{end}}
{{return $href}}
```

Pros:
- Smart handling of links.
- Handles baseURL subpaths automatically.
- Handles language variations automatically.
- Converts invalid links to the configured 404 page (e.g. `refLinksNotFoundURL = "/404.html"`).
- Emits invalid links as warnings or errors, **making it easier for users to adapt to the changes.**

Cons:
- Can't use `..` to refer to parent page (e.g. `../image/`).
- Can't link to site resources (e.g. `/images/favicon.png`).

These cons apply to what I feel are rare cases. Even so, alternative options are available in the form of shortcodes, template functions, and inline `<a>` elements, so it's not like they would become impossible to do.

**Comment by jgazeau** [comment]
> For end-users, it's most important to be able to link to content. That's why I think relref should be used.

You are right, I was not really found of using `ref` or `relref` built-in shortcode, as using the native markdown syntax should be easier and more consistent. But I agree that using `ref` or `relref` should be managed by the theme.

As a consequence, I've changed the behavior to be consistent in all cases (and actually `relref` function is used as you suggested, which also allow to use the `refLinksErrorLevel ` and `refLinksNotFoundURL` configuration):
* I've added an [exhaustive list of links](https://deploy-preview-84--shadocs.netlify.app/markdown/link/) that can be added in a markdown content using the theme. (I hope 😄, so if you find additional ones that should be provided don't hesitate)
* I've added a note on ref and relref usage.

> Additionally, there appears to be a bug with how relref handles trailing slashes. I'd consider this an upstream issue, but it could potentially be resolved here by just trimming the slash:

For that you will see that actually it is working with or without ending slashes.
For example you can use [](image/) or [](image), they will provide the same link.

> Cons:
> 
> Can't use .. to refer to parent page (e.g. ../image/).
> Can't link to site resources (e.g. /images/favicon.png).

I've added the examples in the documentation page and it can be done. 
For the parent page it is actually possible but the syntax is not `../` but `./`, because we are using relref now, and because the Hugo context used in the standard relref built-in function is behaving that way. (You can test it if you want by deleting the link render-hook and also the relref shortcode and use []({{% relref "./" %}}) to redirect to the parent page)

**Comment by Anaminus** [comment]
It's looking very good so far!

The one concern I have is that links with leading slashes aren't validated. For my use-case, most of the pages are generated automatically, so it's a lot easier to use links with leading slashes for these pages. Personally, I have no need to link to site resources, so it would be a lot more valuable to me if *all* non-external links were processed with `relref`.

Perhaps this behavior could be configured? By default, links with a leading slash are processed using the `rel(Lang)URL` method. If this setting is enabled, then links with a leading slash are processed with `relref` instead.

**Comment by jgazeau** [comment]
Well, I would say that in your case you could use relref directly within your link (e.g `[Mylink]({{% relref "/dir/file/" %}})`).
For links able to access resources, IMHO, it can be useful as soon as you put your shared resources within the static folder (I mean shared between languages). But obviously it will depend on how you want to handle them.
So as you suggested I've create the `enforceRefrelLinks` configuration key. If set specifically to true it will then enforce the use of relref to resolve links.
Also FYI I've add a [htmltest](https://github.com/wjdp/htmltest) step to check all links of the documentation website. I've used it on other projects and it can be useful if you want to check the truthfulness of your link. So maybe it will also help you on your project ?

**Comment by Anaminus** [comment]
> So as you suggested I've create the `enforceRefrelLinks` configuration key. If set specifically to true it will then enforce the use of relref to resolve links.

Thank you for this. This will make things a lot easier.

Are links tested with the `baseURL` configured to contain a path? For example, `https://example.com/foo/bar/`. hrefResolver handles baseURL paths correctly, but there are other parts of the theme where links are generated using different methods. One issue I've found is the [taxonomy-selector.html](https://github.com/jgazeau/shadocs/blob/765a45885b8625bd32de65b1f134fcdd3843452b/layouts/partials/theme/taxonomy-selector.html#L14) template, which generates incorrect links only when the baseURL has a path.

**Comment by jgazeau** [comment]
@Anaminus , indeed, thanks for the info, I've also fix some other links that were broken 😃

**Pull request merged**
